name: welcome-message
main: me.carbon.plugins.welcomemessage.WelcomeMessage
version: "1.0.0"
api-version: "1.16"
author: Carbon
description: "A simple plugin that sends a welcome message to anyone joining!"